# Generated by Django 5.0.8 on 2025-02-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='abcde', max_length=500),
            preserve_default=False,
        ),
    ]
