# Generated by Django 5.0.8 on 2025-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurantrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='is_active',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in delivery', 'In Delivery')], default='available', max_length=15),
        ),
    ]
