# Generated by Django 5.0.8 on 2025-04-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_latitude_user_longitude_user_otp_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
    ]
