# Generated by Django 5.0.8 on 2025-02-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Tag slug')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='store.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ('title',),
            },
        ),
    ]
