# Generated by Django 5.0.8 on 2025-02-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_dish_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
