# Generated by Django 5.0.8 on 2025-04-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_notification_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='tracking_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
