# Generated by Django 5.0.8 on 2025-04-19 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartorder_latitude_cartorder_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
