# Generated by Django 5.0.8 on 2025-04-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cartorder_tracking_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='shipping_amount',
        ),
    ]
