# Generated by Django 5.0.8 on 2025-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_review_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_voice_item',
            field=models.BooleanField(default=False),
        ),
    ]
